<Project Sdk="Microsoft.NET.Sdk">
  <!-- Project properties -->
  <PropertyGroup>
    <!-- This is the most appropriate target framework for the game's Unity version. -->
    <TargetFramework>netstandard2.1</TargetFramework>
    <!-- This is the global identifier for your mod. This should not be changed after release. -->
    <AssemblyName>unverifiedhashcode.FoodRemovesCurse</AssemblyName>
    <!-- This is the display name of your mod. -->
    <AssemblyTitle>CookedFoodRemovesCurse</AssemblyTitle>
    <!-- The version number for your assembly, BepInEx plugin, and Thunderstore package. -->
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- ThunderPipe properties -->
  <PropertyGroup>
    <!-- Whether or not this project should build a Thunderstore package. -->
    <IsThunderstorePackable>true</IsThunderstorePackable>
    <!-- Package name on Thunderstore. Must not contain spaces ' ' or dashes '-'. -->
    <ThunderstoreName>CookedFoodRemovesCurse</ThunderstoreName>
    <ThunderstoreDescription>TODO: Fill in short mod description at max 250 characters.</ThunderstoreDescription>
    <!--
      Communities and package categories metadata for publishing with ThunderPipe.
      Communities: https://thunderstore.io/api/experimental/community/
      Categories: https://thunderstore.io/api/experimental/community/peak/category/
    -->
    <ThunderstoreCommunities>peak</ThunderstoreCommunities>
    <ThunderstoreCategories>mods</ThunderstoreCategories>
  </PropertyGroup>

  <!--
    Define mod files to copy to the relative BepInEx directory after build
    and where they are packed to when building a Thunderstore package
  -->
  <ItemGroup>
    <!-- TargetPath is the dll file produced during build. -->
    <ModFile Include="$(TargetPath)" Destination="plugins/" />
    <!--
      If your project needs additional files, e.g. asset bundles,
      you can add them here. Example:

      <ModFile Include="./Assets/bundle" Destination="plugins/" />
    -->
  </ItemGroup>

  <!-- Thunderstore package metadata -->
  <ItemGroup>
    <ThunderstorePackageFile Include="$(SolutionRoot)README.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)CHANGELOG.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)icon.png" />
    <ThunderstorePackageFile Include="$(SolutionRoot)LICENSE" />

    <!--
      A list of Thunderstore packages this package requires at runtime.
      Note: This does NOT mark these as dependencies for this C# project;
            that must be done separately with PackageReference items.
    -->
    <ThunderstoreDependency Include="BepInEx-BepInExPack_PEAK" Version="5.4.75301" />
  </ItemGroup>

  <!--
    To reference mod assemblies from Thunderstore packages via NuGet,
    this project includes the following NuGet feed:
    https://nuget.windows10ce.com/nuget/v3/index.json

    With this, you can simply depend on a Thunderstore package like so:

    <ItemGroup>
      <PackageReference Include="ModTeam-ModName" Version="*" />
    </ItemGroup>

    This will cause the mod to be downloaded and its
    methods will be available at compile time for your code.

    Note that this does NOT mark the package as a dependency
    for your Thunderstore package.
  -->
</Project>
